name: Python Environment

on:
  # To run manually
  push

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v5
    
    - name: Install Python dependencies
      run: |
        python -m pip install matplotlib scipy pandas

    - name: Hello World 
      run: |
        python -c "import pandas as sp; print('Scipy version: '+pd.__version__)"
        python -c "import matplotlib as mpl; print('Matplotlib version: '+mpl.__version__)"
